server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    #表示是否将自己注册进Eureka 默认为true
    register-with-eureka: true
    #表示是否从Eureka拉取注册信息 默认为true
    fetch-registry: true
    service-url: # 配置eureka服务端的地址
      # 单机版本
      # defaultZone: http://localhost:7001/eureka/
      # 集群版本 注意以下的eureka7001.com, eureka7002.com在hosts文件已配置过 其实指向的是本机 127.0.0.1
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/