server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud-db?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    #表示是否将自己注册进Eureka 默认为true
    register-with-eureka: true
    #表示是否从Eureka拉取注册信息 默认为true
    fetch-registry: true
    service-url:
      # 单机版本
      # defaultZone: http://localhost:7001/eureka/
      # 集群版本
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.roytao.springcloud.entity       #所有Entity别名类所在包